properties([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        timestamps()
    }
    triggers{pollSCM("* * * * *")}
    stages {
        stage("Docker_login") {
            steps {
                echo "======= Docker login ======="
                withCredentials([usernamePassword(credentialsId: "dockerhub_cred", usernameVariable: "USER", passwordVariable: "PASSWORD")]){
                    sh "docker login -u $USER -p $PASSWORD"
                }
            }
        }
        stage("Docker_build") {
            steps {
                echo "======= Docker build ======="
                dir("Docker/"){
                    sh "docker build -t bourbol/jumanji:2.0 ."
                }
            }
        }
        stage("Docker_push") {
            steps {
                echo "======= Docker push ======="
                sh "docker push bourbol/jumanji:2.0"
            }
        }
    }
}
