properties ([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        timestamps()
    }
    trigger { pollSCM("* * * * *") }
    stages {
        stage("Just command") {
            steps {
                sh "mkdir /home/rinmamarun/grofalti"
            }
        }
        stage("Docker build") {
            steps {
                dir("Docker/") {
                sh "docker build ."
                }
            }
        }
    }
}
